"""initial migration

Revision ID: 98a530450a14
Revises: f6fcc82da8a0
Create Date: 2024-04-24 19:08:58.760081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a530450a14'
down_revision = 'f6fcc82da8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buying_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('selling_price', sa.Numeric(precision=19, scale=2), nullable=False))
        batch_op.add_column(sa.Column('stock_quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('stock_quantity')
        batch_op.drop_column('selling_price')
        batch_op.drop_column('buying_price')

    # ### end Alembic commands ###
